solution
mate-academy/js_fetch_data_DOM pull request #89
Opened 2021-08-12 18:52 UTC by Bohdan996

- [DEMO LINK](https://Bohdan996.github.io/js_fetch_data_DOM/)

2021-08-13 16:45 UTC, vkryvytskyy requested changes

2021-08-13 16:45 UTC, vkryvytskyy commented on src/scripts/main.js
> +const getPhones = () => {
![image](https://user-images.githubusercontent.com/38065883/129392360-b0f12934-11af-45bc-95ce-657427d2c000.png)
Где phoneDetails и массив id?

2021-08-17 09:00 UTC, mykola-yarchuk submitted a review, later dismissed

2021-08-20 17:29 UTC, vkryvytskyy approved these changes

2022-11-28 07:15 UTC, closed without merging